name: ABAP_702

on:
  push:
    branches: [702]

permissions:
  contents: read

jobs:
  ABAP_702:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
      with:
        ref: 702
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - run: npm ci
    - run: npx abaplint .github/abaplint/abap_702.jsonc